### ISSUE TITLE
Uninstall by deleting Registry entry

### ISSUE THREAD

**Issue by moritztim** [CaffeinatedDragonWare/WindowsHandheldMod#5]
I haven't tried it but you could probably just remove the registry entry instead of changing its value, I'll add that to the readme pr if it's confirmed.

**Comment by CaffeinatedDragonWare** [comment]
Yeah, this does work since in the updated version you have to create a registry entry. This was just a left over from when I was having people manually change the default shell file, before I noticed Windows 11 required you to create one under current user instead.

I updated the readme to reflect this.

**Comment by CaffeinatedDragonWare** [comment]
Updated readme's uninstall instructions to have the user delete the shell file they created under current user rather than changing the value to explorer.exe

**Comment by moritztim** [comment]
> Updated readme's uninstall instructions to have the user delete the shell file they created under current user rather than changing the value to explorer.exe

pls check out my pull request, I made the readme much more structured
